# Generated by Django 5.2.8 on 2025-11-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telega', '0002_auto_20210203_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
